/** Environment variable names — single source of truth */
export const ENV = {
  // Server
  PORT: 'PORT',
  HOST: 'HOST',
  CORS_ORIGINS: 'CORS_ORIGINS',
  PLATFORM_CALLBACK_URL: 'PLATFORM_CALLBACK_URL',
  PLATFORM_API_KEY: 'PLATFORM_API_KEY',
  NODE_ENV: 'NODE_ENV',

  // Game config
  MAX_PLAYERS: 'MAX_PLAYERS',
  GRAVITY: 'GRAVITY',
  JUMP_VELOCITY: 'JUMP_VELOCITY',
  RUNNER_SPEED: 'RUNNER_SPEED',
  OBSTACLE_SPAWN_RATE: 'OBSTACLE_SPAWN_RATE',
  TICK_RATE: 'TICK_RATE',
  DEV_MODE: 'DEV_MODE',

  // World dimensions
  WORLD_WIDTH: 'WORLD_WIDTH',
  WORLD_HEIGHT: 'WORLD_HEIGHT',
  GROUND_Y: 'GROUND_Y',

  // Player dimensions
  PLAYER_WIDTH: 'PLAYER_WIDTH',
  PLAYER_HEIGHT: 'PLAYER_HEIGHT',
  PLAYER_START_X: 'PLAYER_START_X',
  PLAYER_START_Y: 'PLAYER_START_Y',

  // Obstacle dimensions
  GROUND_SMALL_WIDTH: 'GROUND_SMALL_WIDTH',
  GROUND_SMALL_HEIGHT: 'GROUND_SMALL_HEIGHT',
  AIR_HIGH_WIDTH: 'AIR_HIGH_WIDTH',
  AIR_HIGH_HEIGHT: 'AIR_HIGH_HEIGHT',

  // Spawn positions
  OBSTACLE_SPAWN_X: 'OBSTACLE_SPAWN_X',
  AIR_HIGH_SPAWN_Y: 'AIR_HIGH_SPAWN_Y',
} as const;